const CREED=[`No one is more professional than I. I am a noncommissioned officer, a leader of Soldiers. As a noncommissioned officer, I realize that I am a member of a time honored corps, which is known as "The Backbone of the Army". I am proud of the Corps of noncommissioned officers and will at all times conduct myself so as to bring credit upon the Corps, the military service and my country regardless of the situation in which I find myself. I will not use my grade or position to attain pleasure, profit, or personal safety.`,`Competence is my watchword. My two basic responsibilities will always be uppermost in my mind—accomplishment of my mission and the welfare of my Soldiers. I will strive to remain technically and tactically proficient. I am aware of my role as a noncommissioned officer. I will fulfill my responsibilities inherent in that role. All Soldiers are entitled to outstanding leadership; I will provide that leadership. I know my Soldiers and I will always place their needs above my own. I will communicate consistently with my Soldiers and never leave them uninformed. I will be fair and impartial when recommending both rewards and punishment.`,`Officers of my unit will have maximum time to accomplish their duties; they will not have to accomplish mine. I will earn their respect and confidence as well as that of my Soldiers. I will be loyal to those with whom I serve; seniors, peers, and subordinates alike. I will exercise initiative by taking appropriate action in the absence of orders. I will not compromise my integrity, nor my moral courage. I will not forget, nor will I allow my comrades to forget that we are professionals, noncommissioned officers, leaders!`];
let sets=[], selected=0, card=0, reveal=false; let progress=JSON.parse(localStorage.getItem('bqProgress')||'{}');
const app=document.querySelector('#app'), nav=document.querySelector('#nav');
fetch('quizlet_backup_24_sets.json').then(r=>r.json()).then(d=>{sets=d; show('home')}).catch(()=>app.innerHTML='<h2>Could not load study data.</h2><p>Run this site through GitHub Pages or a local web server.</p>');
function esc(s){let t=document.createElement('textarea');t.innerHTML=s;return t.value} function all(){return sets.flatMap((s,si)=>s.cards.map(c=>({...c,si,set:s.set})))}
function save(){localStorage.setItem('bqProgress',JSON.stringify(progress));updateMastered()} function updateMastered(){document.querySelector('#streak').textContent=`${Object.values(progress).filter(x=>x==='known').length} mastered`}
function header(title,sub=''){return `<h1>${title}</h1><div class="sub">${sub}</div>`} function selector(){return `<select id="setSelect">${sets.map((s,i)=>`<option value="${i}" ${i==selected?'selected':''}>${esc(s.set)} (${s.cards.length})</option>`).join('')}</select>`}
function bindSelect(mode){document.querySelector('#setSelect')?.addEventListener('change',e=>{selected=+e.target.value;card=0;reveal=false;show(mode)})}
function show(view){nav.classList.remove('open');[...nav.children].forEach(b=>b.classList.toggle('active',b.dataset.view===view)); if(!sets.length)return;
 if(view==='home'){let total=all().length;app.innerHTML=header('Army Promotion Board Study',`${sets.length} topics · ${total} questions · study anywhere`) + `<div class="toolbar"><button class="primary" onclick="show('board')">Start Board Simulation</button><button class="secondary" onclick="show('creed')">Practice NCO Creed</button></div><div class="grid">${sets.map((s,i)=>`<div class="topic" onclick="selected=${i};show('study')"><small>TOPIC ${String(i+1).padStart(2,'0')}</small><h3>${esc(s.set)}</h3><small>${s.cards.length} questions</small></div>`).join('')}</div>`}
 if(view==='study'){let s=sets[selected];app.innerHTML=header('Study','Review every question and answer in a topic')+selector()+`<div class="toolbar"><button class="primary" onclick="show('flash')">Flashcards</button><button class="secondary" onclick="show('test')">Test this topic</button></div>${s.cards.map(c=>`<div class="box"><b>${c.number}. ${esc(c.question)}</b><p>${esc(c.answer).replace(/\n/g,'<br>')}</p></div>`).join('')}`;bindSelect('study')}
 if(view==='flash')flash(); if(view==='test')test(); if(view==='board')board(); if(view==='creed')creed(); if(view==='progress')stats(); updateMastered()}
function flash(){let s=sets[selected],c=s.cards[card],key=`${selected}-${c.number}`;app.innerHTML=header('Flashcards',`${esc(s.set)} · ${card+1} of ${s.cards.length}`)+selector()+`<div class="progressbar"><i style="width:${(card+1)/s.cards.length*100}%"></i></div><div class="card" onclick="reveal=!reveal;flash()"><div class="question">${esc(c.question)}</div>${reveal?`<div class="answer">${esc(c.answer).replace(/\n/g,'<br>')}</div>`:`<p class="muted">Tap to reveal answer</p>`}</div><div class="toolbar"><button class="secondary" onclick="event.stopPropagation();card=Math.max(0,card-1);reveal=false;flash()">← Previous</button><button class="secondary" onclick="progress['${key}']='review';save()">Review again</button><button class="primary" onclick="progress['${key}']='known';save();card=Math.min(${s.cards.length-1},card+1);reveal=false;flash()">Know it ✓</button><button class="secondary" onclick="card=Math.min(${s.cards.length-1},card+1);reveal=false;flash()">Next →</button></div>`;bindSelect('flash')}
function test(){let pool=sets[selected].cards, q=pool[card%pool.length], others=pool.filter(x=>x!==q).sort(()=>Math.random()-.5).slice(0,3), choices=[q,...others].sort(()=>Math.random()-.5);app.innerHTML=header('Test Mode',esc(sets[selected].set))+selector()+`<div class="box"><small>QUESTION ${card%pool.length+1}</small><h2>${esc(q.question)}</h2>${choices.map(x=>`<button class="choice" onclick="answerTest(this,${x===q})">${esc(x.answer).replace(/\n/g,' · ')}</button>`).join('')}</div><div id="feedback"></div>`;bindSelect('test')}
function answerTest(el,ok){document.querySelectorAll('.choice').forEach(x=>x.disabled=true);el.classList.add(ok?'correct':'wrong');document.querySelector('#feedback').innerHTML=`<div class="toolbar"><b>${ok?'Correct ✓':'Not quite — review this one.'}</b><button class="primary" onclick="card++;test()">Next question →</button></div>`}
function board(){let pool=all(),q=pool[Math.floor(Math.random()*pool.length)];app.innerHTML=header('Board Simulation','Random questions across all study topics')+`<div class="box"><small>${esc(q.set).toUpperCase()}</small><h2>${esc(q.question)}</h2><button class="primary" id="rev">Reveal Answer</button><div id="ans"></div></div>`;document.querySelector('#rev').onclick=()=>{document.querySelector('#ans').innerHTML=`<hr><p style="font-size:20px">${esc(q.answer).replace(/\n/g,'<br>')}</p><div class="toolbar"><button class="secondary" onclick="board()">✕ Incorrect</button><button class="primary" onclick="board()">✓ Correct</button></div>`;document.querySelector('#rev').remove()}}
function creed(mode='read',p=0){let text=CREED[p]; if(mode==='hide'){let n=0;text=text.split(/(\s+)/).map(w=>/^[A-Za-z]/.test(w)&&++n%4===0?`<span class="hiddenword">${w}</span>`:w).join('')} if(mode==='letters')text=text.split(' ').map(w=>w.match(/[A-Za-z]/)?w[0]+'.':w).join(' ');app.innerHTML=header('NCO Creed Training','Read it. Break it down. Recall it. Recite it.')+`<div class="toolbar"><button class="${mode==='read'?'primary':'secondary'}" onclick="creed('read',${p})">Read</button><button class="${mode==='hide'?'primary':'secondary'}" onclick="creed('hide',${p})">Hide Words</button><button class="${mode==='letters'?'primary':'secondary'}" onclick="creed('letters',${p})">First Letters</button><button class="${mode==='type'?'primary':'secondary'}" onclick="creed('type',${p})">Type It</button></div><div class="toolbar">${CREED.map((_,i)=>`<button class="secondary" onclick="creed('${mode}',${i})">Paragraph ${i+1}</button>`).join('')}</div>${mode==='type'?`<div class="box"><p>Type paragraph ${p+1} from memory:</p><textarea id="typed"></textarea><div class="toolbar"><button class="primary" onclick="checkCreed(${p})">Check</button></div><div id="creedResult"></div></div>`:`<div class="box creed">${text}</div>`}`}
function checkCreed(p){let a=document.querySelector('#typed').value.toLowerCase().match(/\b[\w’'-]+\b/g)||[],b=CREED[p].toLowerCase().match(/\b[\w’'-]+\b/g)||[],same=a.filter((x,i)=>x===b[i]).length,score=Math.round(same/b.length*100);document.querySelector('#creedResult').innerHTML=`<h2>${score}% word-position match</h2><p class="muted">Use this as practice feedback, then compare against the original paragraph.</p><button class="secondary" onclick="creed('read',${p})">Show original</button>`}
function stats(){let vals=Object.values(progress),known=vals.filter(x=>x==='known').length,review=vals.filter(x=>x==='review').length,total=all().length;app.innerHTML=header('Progress','Stored privately in this browser')+`<div class="stats"><div class="box"><strong>${known}</strong><br>Mastered</div><div class="box"><strong>${review}</strong><br>Review again</div><div class="box"><strong>${total}</strong><br>Total questions</div></div><div class="toolbar"><button class="secondary" onclick="if(confirm('Reset all saved progress?')){progress={};save();stats()}">Reset progress</button></div>`}
document.querySelector('#menuBtn').onclick=()=>nav.classList.toggle('open');nav.addEventListener('click',e=>{let b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
